### ISSUE TITLE
Unable to detach / terminate

### ISSUE THREAD

**Issue by Deseao** [docker-library/kibana#21]
Docker v 1.9.0
Docker Machine v 0.5.0
Kibana image 4.2.1
docker run -p 5601:5601 --link elastic:elasticsearch -v "$PWD"/kibana/config:/etc/kibana/config kibana:4.2.1

It runs and works, but won't respond to Ctrl + C and Ctrl + P, Ctrl + Q. I have to stop the container from a different shell. If I use docker compose, I get an ERROR: Aborting. when stopping it.

**Comment by yosifkit** [comment]
For `ctrl P and Q` to work you would need a `-t` added to the `docker run`.  It looks like the kibana process does not explicitly handle `SIGINT` or `SIGTERM` and since it is pid 1 in the container, it does not die, hence the `ctrl C` not working.  We could add [`tini`](https://github.com/krallin/tini) to handle the signals, like a few other official images.

**Comment by Deseao** [comment]
Ah, I didn't know that about the -t flag.

**Comment by maticmeznar** [comment]
`docker stop` also doesn't gracefully stop Kibana. It timeouts and kills it after 10 seconds, which makes `docker run` return exit code > 0, which indicates an error, which then leads to problems with the init system if one is used (it usually is in production). Please make this container respect docker best practices.

I think this is an important bug that needs to be fixed ASAP.

**Comment by tianon** [comment]
Looks like we need to add `tini`. :disappointed:  (I tried both `SIGTERM` and `SIGINT` and it doesn't respond to either.)
