### ISSUE TITLE
Kibana plugins

### ISSUE THREAD

**Issue by madeddie** [docker-library/kibana#27]
Since ES 2.0, kibana supports plugins (and needs it, if one wants to keep using marvel).

Has any thought gone into how to tackle that with the docker container?

For now I'm starting kibana container, then exec'ing kibana plugin -i $whatevs on that container and restarting the container, but there must be a more elegant approach.

Perhaps adding some functionality to the docker-entrypoint that takes a list from env and checks if plugin has been installed and if not installs it on startup?

**Comment by madeddie** [comment]
Hmm, also just realised that ES sort of dies when installing a kibana plugin... _scratches head_, not sure how to deal with that in a nice way.

**Comment by tianon** [comment]
It would appear that plugin installation works without Kibana running, so what I'd recommend is actually making a new image that's `FROM kibana` which installs the required plugins; something like:

``` dockerfile
FROM kibana
RUN kibana plugin -i elasticsearch/marvel/latest
```

This should also solve the problem of ES not being happy when a plugin gets installed on the fly since it'll be pre-installed, right?

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with extra plugins.

**Comment by madeddie** [comment]
Well, that would be the sensible solution, yes, but where's the fun in that! ;)

**Comment by madeddie** [comment]
An added problem for creating images per plugin or something is that some plugins are dependent on ES version. So for instance with ES 2.1.0 you could use Kibana 4.3, and Marvel 2.1.0, but with ES 2.1.1, you'd still use Kibana 4.3 but then Marvel 2.1.1. So, while creating an image is a clean enough solution, since plugins for Kibana is here to stay, thinking about a better solution for that might be smart. For now I'll just create my own images.

For people reading this needing the same, make sure you execute it as

> RUN gosu kibana kibana plugin -i elasticsearch/marvel/latest

**Comment by madeddie** [comment]
ok, this will probably not happen

**Comment by wojciechbator** [comment]
Sorry for dusting it out, but I still have a problem installing any kibana plugin. For example I would like to install logtrail plugin with this:

RUN gosu kibana kibana plugin --install https://github.com/sivasamyk/logtrail/#releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip

and instead of logtrail being installed I get "ERROR unknown command plugin", manual for using bin/kibana is displayed and at the end I get this:

ERROR: Service 'kibana' failed to build: The command '/bin/sh -c gosu kibana kibana plugin --install https://github.com/sivasamyk/logtrail/#releases/download/0.1.8/logtrail-5.2.0-0.1.8.zip' returned a non-zero code: 64

It's clear that I don't have anything like kibana plugin installed into container, could you please provide me with some guidance how to fix it and install kibana-plugin feature properly?
