### ISSUE TITLE
Hi, I run this kibana/kibana:7.0.0 but "Kibana server is not ready yet"

### ISSUE THREAD

**Issue by Torah** [docker-library/kibana#91]
expose 5601 is OK with this image?

**Comment by wglambert** [comment]
The image includes that https://github.com/elastic/dockerfiles/blob/2b18a4f9fbbbc5eb06dd1fd79b915f40d3d1c343/kibana/Dockerfile#L26

Expose "functions as a type of documentation . . . about which ports are intended to be published." It doesn't do anything concrete by itself so you'll probably want `-p` to bind the host->container port
https://docs.docker.com/engine/reference/builder/#expose

If you have other questions you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by Torah** [comment]
Thank you a lot! Finally, I see from the terminal of container and find that this image contains only kibana and with no es, so the kibana was finding the 9200 port of es. Then I gave up this image and find another, because I didn't use compose and I need es within kibana. Another question is that how can I install plugins of kibana in version7? The path '/usr/share/bin/kibana' seems been abandoned.
